
export const chatList = [
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }, {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }, {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }, {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }, {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }, {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }, {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Facebook',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 0,
    },
    {
        avatar: 'https://facebook.github.io/react/img/logo.svg',
        alt: 'Reactjs',
        title: 'Yahoo',
        subtitle: 'What are you doing?',
        date: new Date(),
        unread: 1,
    }
]

export const messageList = [
    {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    },{
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    }, {
        position: 'right',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(2020, 10, 1),
    },
    {
        position: 'left',
        type: 'text',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
        date: new Date(),
    },
]