version: "3.3"
services:
    # web:
    #     build: .
    #     ports:
    #         - "8000:80"
    #     depends_on:
    #         - db
    identity:
        image: ${DOCKER_REGISTRY}/nextone/identity:${APP_VERSION:-latest}
        build:
          context: ./src
          dockerfile: ./IdentityService/Dockerfile
        container_name: nextone-identity
        ports:
          - "5102:80"
        restart: unless-stopped
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:5100;http://localhost:5107

    map:
        image: ${DOCKER_REGISTRY}/nextone/map:${APP_VERSION:-latest}
        build:
          context: ./src
          dockerfile: ./MapService/Dockerfile
        container_name: nextone-map
        ports:
          - "5105:80"
        restart: unless-stopped
        volumes:
          - ./Map/MapTiles:/app/Data/MapTiles
          - ./Map/ShapeFiles:/app/Data/ShapeFiles
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:4200;http://localhost:5100;http://localhost:5107
          - IdentityServerOptions__Authority=${IDENTITY_URL}
          - MapSettings__MapOffsetX=0
          - MapSettings__MapOffsetY=-7500
          - MapSettings__MapTilesFolder=Data/MapTiles
          - MapSettings__MapWatcherIntervalInMinutes=5
          
    map-web:
        image: ${DOCKER_REGISTRY}/nextone/map-web:${APP_VERSION:-latest}
        build:
          context: ./src/web-map
          dockerfile: ./Dockerfile
        container_name: nextone-map-web
        ports:
          - "5107:80"
        restart: unless-stopped
        #volumes:
          #- ./configs/mapwebconfig.js:/usr/share/nginx/html/config.js
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}