version: "3.3"
services:
    identity:
        image: ${DOCKER_REGISTRY}/nextone/identity
        build:
          context: ./src
          dockerfile: ./IdentityService/Dockerfile
        container_name: nextone-identity
        ports:
          - "5102:5102"
        restart: unless-stopped
        depends_on:         
          - db
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - IsDBSeed=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:5100;http://localhost:5107;https://${MAPWEB_DOMAIN}
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-identity.rule=Host(`${IDENTITY_DOMAIN}`)"
          - "traefik.http.routers.nextone-identity.entrypoints=https"
          - "traefik.http.routers.nextone-identity.service=nextone-backend"
          - "traefik.http.services.nextone-backend.loadbalancer.server.scheme=http"
          - "traefik.http.services.nextone-backend.loadbalancer.server.port=5102"

    map:
        image: ${DOCKER_REGISTRY}/nextone/map
        build:
          context: ./src
          dockerfile: ./MapService/Dockerfile
        container_name: nextone-map
        ports:
          - "5105:80"
        restart: unless-stopped
        depends_on:         
          - db
        volumes:
          - ./Map/MapTiles:/app/Data/MapTiles
          - ./Map/ShapeFiles:/app/Data/ShapeFiles
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:4200;http://localhost:5100;http://localhost:5107;https://${MAPWEB_DOMAIN}
          - IdentityServerOptions__Authority=${IDENTITY_URL}
          - IdentityServerOptions__RequireHttpsMetadata=false
          - MapSettings__MapOffsetX=0
          - MapSettings__MapOffsetY=-7500
          - MapSettings__MapTilesFolder=Data/MapTiles
          - MapSettings__MapWatcherIntervalInMinutes=5
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-map.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/nextone/map`)"
          - "traefik.http.routers.nextone-map.middlewares=nextone-map-stripprefix"
          - "traefik.http.middlewares.nextone-map-stripprefix.stripprefix.prefixes=/nextone/map"
          - "traefik.http.routers.nextone-map.entrypoints=https"

    map-web:
        image: ${DOCKER_REGISTRY}/nextone/map-web
        build:
          context: ./src/web-map
          dockerfile: ./Dockerfile
        container_name: nextone-map-web
        ports:
          - "5107:80"
        restart: unless-stopped
        volumes:
          - ./configs/mapwebconfig.js:/usr/share/nginx/html/config.js
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
        networks:
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-mapweb.rule=Host(`${MAPWEB_DOMAIN}`)"
          - "traefik.http.routers.nextone-mapweb.entrypoints=https"
          
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest #"mcr.microsoft.com/mssql/server"
        container_name: nextone-mssql
        environment:
            SA_PASSWORD: "NextOne@123456"
            ACCEPT_EULA: "Y"
        restart: always
        networks:
          - nextone-internal
        ports:
          - "1435:1433"
        volumes:
        #- ./devvolumes/db/backup:/var/opt/mssql/backup
        #- ./devvolumes/db/data:/var/opt/mssql/data
        #- ./devvolumes/db/log:/var/opt/mssql/log
        - db-data:/var/opt/mssql/data

networks:
  traefik-proxy:
    external: true
  nextone-internal:
    external: false
volumes:
  db-data: