version: "3.3"
services:
    identity:
        image: ${DOCKER_REGISTRY}/nextone/identity:latest
        #pull_policy: always
        build:
          context: ./src
          dockerfile: ./IdentityService/Dockerfile
        container_name: nextone-identity
        ports:
          - "5102:5102"
        restart: unless-stopped
        depends_on:         
          - nextonedb
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - IsDBSeed=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:5100;http://localhost:5107;http://${MAPWEB_DOMAIN};http://${COMWEB_DOMAIN}
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-identity.rule=Host(`${IDENTITY_DOMAIN}`)"
          - "traefik.http.routers.nextone-identity.entrypoints=http,https"
          - "traefik.http.routers.nextone-identity.service=nextone-identity"
          - "traefik.http.services.nextone-identity.loadbalancer.server.scheme=http"
          - "traefik.http.services.nextone-identity.loadbalancer.server.port=5102"


    com:
        image: ${DOCKER_REGISTRY}/nextone/com:latest
        build:
          context: ./src
          dockerfile: ./ComService/Dockerfile
        container_name: nextone-com
        ports:
          - "5104:80"
        restart: unless-stopped
        depends_on:         
          - nextonedb
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:4200;http://localhost:5100;http://localhost:5107;http://${COMWEB_DOMAIN};https://${COMWEB_DOMAIN}
          - IdentityServerOptions__Authority=${IDENTITY_LOCAL}
          - IdentityServerOptions__RequireHttpsMetadata=false
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-com.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/nextone/com`)"
          - "traefik.http.routers.nextone-com.middlewares=nextone-com-stripprefix"
          - "traefik.http.middlewares.nextone-com-stripprefix.stripprefix.prefixes=/nextone/com"
          - "traefik.http.routers.nextone-com.entrypoints=http,https"
        
    master:
        image: ${DOCKER_REGISTRY}/nextone/master:latest
        build:
          context: ./src
          dockerfile: ./MasterService/Dockerfile
        container_name: nextone-master
        ports:
          - "5103:5103"
        restart: unless-stopped
        depends_on:         
          - nextonedb
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:4200;http://localhost:5100;http://localhost:5107;http://${COMWEB_DOMAIN};https://${COMWEB_DOMAIN}
          - IdentityServerOptions__Authority=${IDENTITY_LOCAL}
          - IdentityServerOptions__RequireHttpsMetadata=false
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-master.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/nextone/master`)"
          - "traefik.http.routers.nextone-master.middlewares=nextone-master-stripprefix"
          - "traefik.http.middlewares.nextone-master-stripprefix.stripprefix.prefixes=/nextone/master"
          - "traefik.http.routers.nextone-master.entrypoints=http,https"
          - "traefik.http.routers.nextone-master.service=nextone-master"
          - "traefik.http.services.nextone-master.loadbalancer.server.scheme=http"
          - "traefik.http.services.nextone-master.loadbalancer.server.port=5103"
          
    map:
        image: ${DOCKER_REGISTRY}/nextone/map:latest
        build:
          context: ./src
          dockerfile: ./MapService/Dockerfile
        container_name: nextone-map
        ports:
          - "5105:80"
        restart: unless-stopped
        depends_on:         
          - nextonedb
        volumes:
          #- ./Map/MapTiles:/app/Data/MapTiles
          #- ./Map/ShapeFiles:/app/Data/ShapeFiles
          - map-data:/app/Data
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:4200;http://localhost:5100;http://localhost:5107;http://${MAPWEB_DOMAIN};https://${MAPWEB_DOMAIN};http://${COMWEB_DOMAIN};https://${COMWEB_DOMAIN}
          - IdentityServerOptions__Authority=${IDENTITY_LOCAL}
          - IdentityServerOptions__RequireHttpsMetadata=false
          - MapSettings__MapOffsetX=0
          - MapSettings__MapOffsetY=-7500
          - MapSettings__MapTilesFolder=Data/MapTiles
          - MapSettings__MapWatcherIntervalInMinutes=5
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-map.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/nextone/map`)"
          - "traefik.http.routers.nextone-map.middlewares=nextone-map-stripprefix"
          - "traefik.http.middlewares.nextone-map-stripprefix.stripprefix.prefixes=/nextone/map"
          - "traefik.http.routers.nextone-map.entrypoints=http,https"
      
    file:
        image: ${DOCKER_REGISTRY}/nextone/file:latest
        build:
          context: ./src
          dockerfile: ./FileService/Dockerfile
        container_name: nextone-file
        ports:
          - "5106:80"
        restart: unless-stopped
        depends_on:         
          - nextonedb
        volumes:
          #- ./File/Uploads:/app/Data/Uploads
          - file-uploads:/app/Data/Uploads
        environment:
          - TZ=Asia/Ho_Chi_Minh
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
          - IsAutoMigration=true
          - Logging__LogLevel__Default=Information
          - CorsHosts=http://localhost:4200;http://localhost:5100;http://localhost:5107;http://${COMWEB_DOMAIN};https://${COMWEB_DOMAIN}
          - IdentityServerOptions__Authority=${IDENTITY_LOCAL}
          - IdentityServerOptions__RequireHttpsMetadata=false
          - LocalFileSettings__FileFolder=Data/Uploads
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-file.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/nextone/file`)"
          - "traefik.http.routers.nextone-file.middlewares=nextone-file-stripprefix"
          - "traefik.http.middlewares.nextone-file-stripprefix.stripprefix.prefixes=/nextone/file"
          - "traefik.http.routers.nextone-file.entrypoints=http,https"
              
    map-web:
        image: ${DOCKER_REGISTRY}/nextone/map-web:latest
        build:
          context: ./src/web-map
          dockerfile: ./Dockerfile
        container_name: nextone-map-web
        ports:
          - "5107:80"
        restart: unless-stopped
        volumes:
          - ./configs/mapwebconfig.js:/usr/share/nginx/html/config.js
          
        environment:
          - TZ=Asia/Ho_Chi_Minh
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-mapweb.rule=Host(`${MAPWEB_DOMAIN}`)"
          - "traefik.http.routers.nextone-mapweb.entrypoints=http,https"
          
    com-web:
        image: ${DOCKER_REGISTRY}/nextone/com-web:latest
        build:
          context: ./src/web
          dockerfile: ./Dockerfile
        container_name: nextone-com-web
        ports:
          - "5100:80"
        restart: unless-stopped
        volumes:
          - ./configs/comwebconfig.js:/usr/share/nginx/html/config.js
          
        environment:
          - TZ=Asia/Ho_Chi_Minh
        networks:
          - nextone-internal
          - traefik-proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextone-mapweb.rule=Host(`${COMWEB_DOMAIN}`)"
          - "traefik.http.routers.nextone-mapweb.entrypoints=http,https"

    nextonedb:
        image: mcr.microsoft.com/mssql/server:2017-latest #"mcr.microsoft.com/mssql/server"
        container_name: nextone-mssql
        environment:
            SA_PASSWORD: "NextOne@123456"
            ACCEPT_EULA: "Y"
        restart: always
        networks:
          - nextone-internal
        ports:
          - "1435:1433"
        volumes:
        #- ./devvolumes/db/backup:/var/opt/mssql/backup
        #- ./devvolumes/db/data:/var/opt/mssql/data
        #- ./devvolumes/db/log:/var/opt/mssql/log
        - db-data:/var/opt/mssql/data
        
    nginx:
        image: nginx:alpine
        container_name: nextone-nginx
        restart: always
        environment:
          - TZ=Asia/Ho_Chi_Minh
        ports:
          - "80:80"
          - "443:443"
        volumes:
          #- ./configs/nginx.conf:/etc/nginx/nginx.conf
          - ./configs/nginx-proxy-map.conf:/etc/nginx/nginx.conf
          - ./configs/certificates:/ca-certificates
        networks:
          - nextone-internal
        

networks:
  traefik-proxy:
    external: false
  nextone-internal:
    external: false
    
volumes:
  db-data:
  file-uploads:
  map-data: