version: "3.9"
services:
    # web:
    #     build: .
    #     ports:
    #         - "8000:80"
    #     depends_on:
    #         - db
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest #"mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "NextOne@123456"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
        - ./devvolumes/db/backup:/var/opt/mssql/backup
        - ./devvolumes/db/data:/var/opt/mssql/data
        - ./devvolumes/db/log:/var/opt/mssql/log
        deploy:
            resources:
                limits:
                    memory: 4G
    seq:
        image: datalust/seq:latest
        environment:
            - ACCEPT_EULA=Y
            #- BASE_URI=https://seq.dptsprotrans.com
            #- SEQ_FIRSTRUN_ADMINPASSWORDHASH="$PH"
        ports:
            - "5109:80"
            - "5341:5341"
        #volumes:
        #    /path/to/seq/data:/data
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 1G