pipeline {
  agent any
  // agent {
  //   //label 'master'
  //   //docker { image 'node:latest' }
  //   //dockerfile true
  // }
  environment {
    registryCredential = 'harbor.tris.vn'
	DOCKER_REGISTRY = 'harbor.tris.vn'
	
    CONTAINER_NAME = 'test-jenkins-node-service'
    ACTION_TYPE = sh(script: "echo \"${env.gitlabActionType}\" | sed 's|/|-|g'", returnStdout: true).trim().toLowerCase()
    PARSED_VERSION = sh(returnStdout: true, script: "git log -1 | sed -r 's/[[:alnum:]]+=/\\n&/g' | awk -F= '{if(\$1==\"VERSION\"){print \$2} else {print \"\"}}' | sed ':a;N;\$!ba;s/\\n//g' | awk '{if(\$1==\"\"){print \"latest\"} else {print \$1}}'").trim()
    APP_VERSION = sh(script: "echo \"$PARSED_VERSION\"", returnStdout: true)
	
	MAT_KHAU1 = credentials('MAT_KHAU')
  }

  stages {
    stage('Info') {
      steps {
        echo "Current build number: ${currentBuild.number}"
        withCredentials([string(credentialsId: 'MAT_KHAU', variable: 'MAT_KHAU')]) {
			sh 'echo "MAT_KHAU: ${MAT_KHAU}, - ${MAT_KHAU1}"'
		}
		script {
            def commit = sh(returnStdout: true, script: 'git log -1 --pretty=%B | cat')
            echo "Last commit : ${commit}"
            echo "APP_VERSION : ${APP_VERSION}"
            echo "BUILD_NUMBER : ${BUILD_NUMBER}"
        }
      }
    }
    stage('NextOne'){
      parallel{
          stage('MapService') {
            when{ 
              anyOf{
                changeset "cicd/jenkins/Jenkinsfile"
                changeset 'src/MapService/**'
                expression { service == 'map'}
              }
              
            }
            stages {
              stage('MapService-Build'){
                // agent {
                //     docker { image 'node:latest' }
                // }
                // environment {
                //   HOME = '.'
                // }
                steps {
                  sh "APP_VERSION=${BUILD_NUMBER} docker-compose build map"
                }
              }

              stage('MapService-Release'){
                  steps {
                    //sh 'docker tag ${DOCKER_REGISTRY}/nextone/map ${DOCKER_REGISTRY}/dataapi:version
                    withCredentials([usernamePassword( credentialsId: "${registryCredential}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'docker login -u ${USERNAME} -p ${PASSWORD} ${registryCredential}'
                        sh 'docker push hub.tris.vn/nextone/map:${BUILD_NUMBER}'
                    }
                  }
              }

              // stage('MapService-Clean'){
              //   steps{
              //     sh "APP_VERSION=${BUILD_NUMBER} docker-compose down map --rmi 'all' || true"
              //   }
              // }

              stage('MapService-DeployStaging') {
                when {
                  expression { GIT_BRANCH == 'origin/main' }
                }
                steps {
                  sh "docker-compose -f docker-compose.yml up -d map"
                }
              }

              // stage('MapService-SystemTest') {
              //   steps{
              //     echo 'system test'
              //   }
              // }
            }
          }

          stage('MapWeb') {
            when{ 
              anyOf {
                changeset "cicd/jenkins/Jenkinsfile"
                changeset "src/web-map/**"
                expression { service == 'map-web'}
              }
            }
            stages {
              stage('MapWeb-Build'){
                // agent {
                //     docker { image 'node:latest' }
                // }
                // environment {
                //   HOME = '.'
                // }
                steps {
                  sh "APP_VERSION=${BUILD_NUMBER} docker-compose build map-web"
                }
              }

              stage('MapWeb-Release'){
                  steps {
                    withCredentials([usernamePassword( credentialsId: "${registryCredential}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'docker login -u ${USERNAME} -p ${PASSWORD} ${registryCredential}'
                        sh 'docker push ${DOCKER_REGISTRY}/nextone/map-web:${BUILD_NUMBER}'
                    }
                  }
              }

              stage('MapWeb-DeployStaging') {
                when {
                  expression { GIT_BRANCH == 'origin/main' }
                }
                steps {
                  sh "docker-compose -f docker-compose.yml up -d map-web"
                }
              }
              
            }
          }

          stage('IdentityService') {
            when{ 
              anyOf {
                changeset "cicd/jenkins/Jenkinsfile"
                changeset "src/Identity/**"
                changeset "src/SharedDomain/**"
                changeset "src/Libs/NextOne.Shared/**"
                changeset "src/Libs/NextOne.Infrastructure.Core/**"
                expression { service == 'identity'}
              }
            }
            stages {
              stage('IdentityService-Build'){
                // agent {
                //     docker { image 'node:latest' }
                // }
                // environment {
                //   HOME = '.'
                // }
                steps {
                  sh "APP_VERSION=${BUILD_NUMBER} docker-compose build identity"
                }
              }

              stage('IdentityService-Release'){
                  steps {
                    withCredentials([usernamePassword( credentialsId: "${registryCredential}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'docker login -u ${USERNAME} -p ${PASSWORD} ${registryCredential}'
                        sh 'docker push ${DOCKER_REGISTRY}/nextone/identity:${BUILD_NUMBER}'
                    }
                  }
              }

              // stage('IdentityService-Clean'){
              //   steps{
              //     sh "APP_VERSION=${BUILD_NUMBER} docker-compose down identity --rmi 'all' || true"
              //   }
              // }

              stage('IdentityService-DeployStaging') {
                when {
                  expression { GIT_BRANCH == 'origin/main' }
                }
                steps {
                  sh "docker-compose -f docker-compose.yml up -d identity"
                }
              }
            }
          }
      }
    }

  }

  post {
    success {
      script {
        sh 'echo Pipeline successfully run'
      }
    }
    always {
      sh 'echo Done'
    }
  }
}
