name: myapplication
services:
- name: Gateway
  project: Gateway/Gateway.csproj
  tags:
    - gateway
    - core
  replicas: 1
  bindings:
  - port: 5101
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
 
- name: IdentityService
  project: IdentityService/IdentityService.csproj
  tags:
    - identity
    - core
  replicas: 1
  bindings:
  - port: 5102
    protocol: https
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  
- name: MasterService
  project: MasterService/MasterService.csproj
  tags:
    - master
    - core
  replicas: 1
  bindings:
  - name: http
    protocol: http
    port: 5103
  - name: grpc
    port: 15103
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
    
- name: ComService
  project: ComService/ComService.csproj
  tags:
    - com
    - core
  replicas: 1
  bindings:
  - port: 5104
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development 
  
- name: MapService
  project: MapService/MapService.csproj
  tags:
    - map
  replicas: 1
  bindings:
  - port: 5105
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development 
 
- name: FileService
  project: FileService/FileService.csproj
  tags:
    - file
    - core
  replicas: 1
  bindings:
  - port: 5106
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development 
    
- name: rabbit
  image: rabbitmq:3-management
  tags:
    - rabbit
    - infra
  bindings:
    - port: 5672
      protocol: rabbitmq